version: 2

models:
  - name: dim_channels
    description: |
      Dimension table for Telegram channels with surrogate keys.
      **Grain**: One row per unique channel.
      **Use Cases**:
      - Channel-level analytics and comparisons
      - Channel metadata and statistics
    columns:
      - name: channel_key
        description: "Surrogate key for channel dimension"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Business key: Telegram channel name"
        tests:
          - unique
          - not_null
      - name: first_message_date
        description: "Date of first message from this channel"
      - name: last_message_date
        description: "Date of most recent message from this channel"
      - name: total_messages
        description: "Total number of messages from this channel"

  - name: dim_dates
    description: |
      Date dimension table with calendar attributes for time-based analysis.
      **Grain**: One row per calendar day (2020-2030).
      **Use Cases**:
      - Time-based analysis and trending
      - Day-of-week, month, quarter aggregations
    columns:
      - name: date_key
        description: "Surrogate key: date in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date (DATE type)"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year (e.g., 2024)"
      - name: quarter
        description: "Quarter (1-4)"
      - name: month
        description: "Month (1-12)"
      - name: week
        description: "Week number (ISO week)"
      - name: day_of_month
        description: "Day of month (1-31)"
      - name: day_of_week
        description: "Day of week (1=Monday, 7=Sunday)"
      - name: day_name
        description: "Day name (Monday, Tuesday, etc.)"
      - name: is_weekend
        description: "Boolean flag: true if Saturday or Sunday"

  - name: fct_messages
    description: |
      Fact table for Telegram messages with foreign keys to dimensions.
      **Grain**: One row per message.
      **Use Cases**:
      - Message-level analytics
      - Volume analysis by channel and date
      - Engagement metrics (views, forwards)
      - Content analysis (message length, media presence)
    columns:
      - name: message_id
        description: "Unique Telegram message ID (business key)"
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: message_timestamp
        description: "Full timestamp of message"
      - name: message_text
        description: "Text content of message"
      - name: message_length
        description: "Character length of message text"
      - name: views
        description: "Number of views"
        tests:
          - not_null
      - name: forwards
        description: "Number of forwards"
        tests:
          - not_null
      - name: has_media
        description: "Boolean: message contains media"
      - name: has_image
        description: "Boolean: message has downloadable image"
      - name: image_path
        description: "Path to image file"
